import React from "react";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  ImageIconStyle: {
    margin: 32,
    height: 64,
    width: 64,
    resizeMode: "stretch",
  },
  ImageIconSmallStyle: {
    margin: 16,
    height: 48,
    width: 48,
    resizeMode: "stretch",
  },
  ImageStyle: {
    margin: 16,
    height: 100,
    width: 100,
    resizeMode: "stretch",
  },
  TextStyle: {
    marginBottom: 4,
    marginRight: 3,
    fontSize: 16,
    fontWeight: "bold",
  },
  ButtonTrangchuStyle: {
    width: "94%",
    flexDirection: "row",
    alignItems: "center",
    alignContent: "center",
    borderWidth: 3,
    borderColor: "#ccccff",
    height: 72,
    borderRadius: 100,
    margin: 5,
    marginBottom: "1%",
  },
  ButtonTracuuStyle: {
    width: "48%",
    flexDirection: "row",
    alignItems: "center",
    alignContent: "center",
    borderWidth: 3,
    borderColor: "#ccccff",
    height: 60,
    margin: 5,
    borderRadius: 100,
    marginBottom: "1%",
  },
  ButtonBanglaiStyle: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    alignContent: "center",
    borderBottomWidth: 1,
    borderColor: "#ccccff",
    height: 72,
  },
  ButtonBanglaiPressedStyle: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    alignContent: "center",
    borderWidth: 2,
    borderColor: "#8c1aff",
    height: 72,
  },
  ButtonBienbaoStyle: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    alignContent: "center",
    borderBottomWidth: 2,
    borderColor: "#ccccff",
    height: 100,
    borderRadius: 0,
  },
  CauhoiStyle: {
    flex: 1,
  },
  paginationStyle: {
    position: "absolute",
    bottom: 10,
    right: 10,
  },
  paginationText: {
    fontSize: 20,
  },
  CautraloiOnclick: {
    borderWidth: 2,
    borderColor: "#8c1aff",
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: "7%",
  },
  CautraloiUnclick: {
    borderWidth: 0,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: "7%",
  },
  CautraloiDung: {
    borderWidth: 3,
    borderColor: "#00cc00",
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: "7%",
  },
  CautraloiSai: {
    borderWidth: 2,
    borderColor: "#ff6666",
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: "7%",
  },
  hintStyle: {
    width: "93%",
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    alignContent: "center",
    borderWidth: 5,
    borderBottomWidth: 0,
    borderRightWidth: 0,
    borderColor: "#ccccff",
    height: 40,
    marginTop: "5%",
    borderRadius: 100,
  },
  meoStyle: {
    margin: 2,
    marginLeft: "3%",
    marginRight: "4%",
    fontSize: 17,
  },
  meoContainer: {
    borderLeftWidth: 5,
    borderColor: "#ccccff",
    borderBottomLeftRadius: 10,
    borderTopLeftRadius: 10,
    marginLeft: "3%",
  },
});
